services:
  backend:
    profiles:
      - dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command:
      ["fastapi", "dev", "main.py", "--port", "5200", "--host", "0.0.0.0"]
    volumes:
      - ./backend:/app
    environment:
      - WATCHFILES_FORCE_POLLING=true

  frontend:
    profiles:
      - dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - ./frontend:/app
      - frontend-node-modules:/app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  frontend-node-modules:
