FROM python:3.13-slim-bookworm
WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

RUN pip install --no-cache-dir uv

COPY pyproject.toml uv.lock ./
RUN uv sync --locked

COPY . .

EXPOSE 5200

CMD ["/app/.venv/bin/fastapi", "dev", "main.py", "--host", "0.0.0.0", "--port", "5200"]
